
#line 3 "config-lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (size_t) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 95
#define YY_END_OF_BUFFER 96
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[393] =
    {   0,
       93,   93,   96,   94,   93,   92,   94,    2,   94,   85,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       93,   92,    0,    3,    2,    1,    2,   85,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   14,
        0,    0,    0,    0,   72,    0,    0,    0,    0,   77,
        0,    0,    0,    0,    0,    0,   90,    0,   88,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   59,    0,    0,    0,    0,

        0,    0,    0,   16,    0,   18,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   91,
        0,   29,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   87,    4,    0,    0,
       67,    0,    0,   58,    0,    0,    0,    0,    0,   61,
       78,    0,    0,    0,    0,   19,    0,    0,    0,    0,
       21,    0,   22,    0,   25,    0,   28,    0,    0,    0,
        0,   34,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   86,   48,   49,    0,   57,

        0,   53,    0,    0,   66,    0,    0,    0,    0,    0,
        0,    0,   89,   60,    0,    0,   71,    0,   17,    0,
       76,    0,    0,   55,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   39,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   51,   56,    0,   52,
        0,    0,    0,    0,    0,    0,    0,    0,   13,    0,
       15,   70,    0,    0,   75,    0,   63,   54,    0,    0,
       27,    0,    0,    0,    0,    0,    0,    0,    0,   83,
        0,    0,   65,    0,   43,   80,   81,    0,    0,    0,
        0,    0,    0,    7,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,   62,    0,    0,   30,    0,   32,
       33,    0,    0,    0,    0,   40,   41,   64,    0,    0,
       47,    0,   82,    0,    0,    0,    0,   12,    0,    0,
       84,   79,   69,   20,   74,   23,   26,   31,   35,    0,
       37,    0,   42,    0,    0,    0,   50,    0,    6,    8,
        0,    0,    0,   68,   73,    0,    0,    0,   44,    0,
        0,    0,   11,    0,    0,    0,    0,    0,    0,    0,
        5,    9,   10,    0,   36,    0,   45,    0,    0,    0,
        0,    0,    0,   46,    0,    0,    0,    0,   24,    0,
       38,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    1,
        1,    6,    1,    1,    1,    1,    7,    8,    8,    8,
        8,    9,   10,    8,    8,    8,    8,    1,    1,    1,
        1,    1,    1,    1,   11,   12,   13,   14,   15,   16,
       17,   18,   19,    1,   20,   21,   22,   23,   24,   25,
        1,   26,   27,   28,   29,   30,   31,   32,   33,    1,
        1,    1,    1,    1,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,    1,   44,   45,   46,   47,
       48,   49,    1,   50,   51,   52,   53,   54,   55,   56,
       57,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[58] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[396] =
    {   0,
        0,    0,  230,  786,  167,    0,   55,    0,   54,   54,
       34,   55,   49,   57,   37,   60,   51,   55,   94,  129,
       99,  103,  167,   72,  112,  155,   43,   59,  116,   69,
      165,    0,   82,  786,    0,  786,    0,  148,  110,   99,
      150,  135,  159,  148,  140,  148,  161,  164,  159,  786,
      154,  156,  159,  179,  163,  168,  188,  192,  187,  185,
      204,  199,  209,  202,  209,  214,  200,  213,  786,  239,
      204,  208,  222,  213,  216,  246,  212,  233,  249,  236,
      240,  247,  241,  249,  261,  253,  264,  257,  278,  249,
      128,  271,  272,  265,  269,  270,  290,  296,  287,  283,

      288,  290,  298,  786,  290,  786,  295,  297,  302,  120,
      295,  314,  298,  313,  302,  317,  322,  316,  318,  786,
      314,  786,  326,  321,  334,  337,  327,  329,  344,  338,
      342,  338,  344,  344,  356,  341,  353,  358,  361,  363,
      365,  357,  357,  365,  371,  367,  786,  786,  367,  378,
      374,  380,  379,  786,  385,  395,  388,  388,  399,  388,
      391,  390,  404,  409,  409,  786,  400,  413,  419,  404,
      786,  415,  786,  425,  414,  431,  786,  422,  418,  427,
      434,  786,  430,  430,  436,  438,  429,  448,  443,  444,
      447,  456,  445,  459,  452,  786,  786,  456,  452,  454,

      473,  462,  469,  473,  786,  482,  484,   98,  487,  483,
      494,  479,  786,  786,  485,  495,  484,  479,  786,  499,
      488,  484,  504,  493,  509,  509,  512,  505,  505,  506,
      516,  527,  523,  534,  524,  786,  523,  526,  539,  541,
      546,  532,  107,  531,  531,  551,  786,  786,  535,  786,
      545,  548,  547,  553,  560,  551,  553,  553,  786,  553,
      786,  786,  557,  579,  786,  565,  568,  786,  579,  572,
      786,  575,  577,  583,  591,  583,  586,  588,  596,  786,
      596,  589,  589,  599,  786,  786,  786,   95,  592,  601,
      609,  602,  601,  786,  618,  610,  614,  622,  628,  613,

      618,  635,  637,  638,  786,  639,  625,  786,  642,  786,
      786,  637,  644,  646,  650,  786,  786,  786,  643,  665,
      786,  656,  786,  648,  645,  644,  657,  786,  664,  665,
      786,  786,  664,  786,  666,   90,  786,  786,  786,  670,
      786,  670,  786,  674,  677,  674,  786,  672,  786,  786,
      682,  687,  678,  786,  786,  683,  682,  693,  786,  693,
      694,  698,  786,  696,  701,  717,  706,  714,  710,  720,
      786,  786,  786,  728,  786,  713,  786,  719,  717,  732,
      732,  731,  725,  786,  731,  724,  741,  746,  786,  738,
      786,  786,   81,  783,   71

    } ;

static yyconst flex_int16_t yy_def[396] =
    {   0,
      392,    1,  392,  392,  392,  393,  394,  395,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  393,  394,  392,  395,  392,  395,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,

      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,

      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,

      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,    0,  392,  392,  392

    } ;

static yyconst flex_int16_t yy_nxt[844] =
    {   0,
        4,    5,    6,    7,    8,    4,    9,   10,   10,   10,
       11,   12,   13,   14,   15,   16,    4,   17,   18,   19,
        4,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,    4,   30,    4,   11,   12,   13,   14,   15,   16,
        4,   17,   18,   19,    4,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,    4,   30,   34,   34,   36,
       37,   38,   38,   38,   39,   40,   43,   45,   48,   85,
       49,   35,   44,   50,   51,   41,   86,   53,   52,   46,
       54,   32,   47,   89,   34,   34,   76,   42,   39,   40,
       43,   45,   48,   85,   49,   77,   44,   50,   51,   41,

       86,   53,   52,   46,   54,   55,   47,   89,   56,   64,
       76,   42,   57,   65,   58,  286,  287,   66,   68,   77,
       90,   91,   67,  356,   78,   69,   79,   70,  320,   55,
       87,  255,   56,   64,   88,   80,   57,   65,   58,   59,
       60,   66,   68,   61,   90,   91,   67,   62,   78,   69,
       79,   70,   63,  167,   87,   38,   38,   38,   88,   80,
       92,  149,   93,   59,   60,   81,   31,   61,   31,   94,
       95,   62,   96,   82,   97,   98,   63,   71,   99,  100,
       83,   72,  101,  102,   92,   73,   93,   84,  103,   81,
       74,  104,   75,   94,   95,  105,   96,   82,   97,   98,

      106,   71,   99,  100,   83,   72,  101,  102,  107,   73,
      108,   84,  103,  109,   74,  104,   75,  111,  110,  105,
      112,  113,  114,  116,  106,  117,  118,  119,  120,  392,
      124,  115,  107,  125,  108,  126,  392,  109,  127,  128,
      132,  111,  110,  133,  112,  113,  114,  116,  137,  117,
      118,  119,  120,  121,  124,  115,  129,  125,  130,  126,
      122,  134,  127,  128,  132,  138,  123,  133,  139,  140,
      131,  135,  137,  141,  136,  142,  143,  121,  144,  145,
      129,  148,  130,  150,  122,  134,  151,  152,  146,  138,
      123,  153,  139,  140,  131,  135,  154,  141,  136,  142,

      143,  155,  144,  145,  147,  148,  157,  150,  158,  159,
      151,  152,  146,  160,  161,  153,  162,  163,  164,  165,
      154,  166,  168,  156,  169,  155,  170,  171,  147,  172,
      157,  173,  158,  159,  174,  175,  176,  160,  161,  177,
      162,  163,  164,  165,  178,  166,  168,  179,  169,  180,
      170,  171,  181,  172,  182,  173,  183,  184,  174,  175,
      176,  186,  187,  177,  185,  188,  189,  190,  178,  191,
      192,  179,  193,  180,  194,  195,  181,  196,  182,  197,
      183,  184,  198,  199,  200,  186,  187,  201,  185,  188,
      189,  190,  202,  191,  192,  203,  193,  204,  194,  195,

      205,  196,  206,  197,  207,  208,  198,  199,  200,  211,
      209,  201,  212,  213,  214,  215,  202,  216,  217,  203,
      218,  204,  210,  219,  205,  220,  206,  221,  207,  208,
      222,  223,  224,  211,  209,  225,  212,  213,  214,  215,
      226,  216,  217,  227,  218,  228,  210,  219,  229,  220,
      230,  221,  231,  232,  222,  223,  224,  233,  234,  225,
      235,  236,  237,  238,  226,  239,  240,  227,  241,  228,
      242,  243,  229,  244,  230,  245,  231,  232,  246,  247,
      248,  233,  234,  249,  235,  236,  237,  238,  250,  239,
      240,  251,  241,  252,  242,  243,  253,  244,  254,  245,

      256,  257,  246,  247,  248,  258,  259,  249,  260,  261,
      262,  263,  250,  264,  265,  251,  266,  252,  267,  268,
      253,  269,  254,  270,  256,  257,  271,  272,  273,  258,
      259,  274,  260,  261,  262,  263,  275,  264,  265,  276,
      266,  277,  267,  268,  278,  269,  279,  270,  280,  281,
      271,  272,  273,  282,  283,  274,  284,  285,  288,  289,
      275,  290,  291,  276,  292,  277,  293,  294,  278,  295,
      279,  298,  280,  281,  299,  296,  300,  282,  283,  301,
      284,  285,  288,  289,  302,  290,  291,  297,  292,  303,
      293,  294,  304,  295,  305,  298,  306,  307,  299,  296,

      300,  308,  309,  301,  310,  311,  312,  313,  302,  314,
      315,  297,  316,  303,  317,  318,  304,  319,  305,  321,
      306,  307,  322,  323,  324,  308,  309,  325,  310,  311,
      312,  313,  326,  314,  315,  327,  316,  328,  317,  318,
      329,  319,  330,  321,  331,  332,  322,  323,  324,  333,
      334,  325,  335,  336,  337,  338,  326,  339,  340,  327,
      341,  328,  342,  343,  329,  392,  330,  392,  331,  332,
      347,  348,  349,  333,  334,  350,  335,  336,  337,  338,
      351,  339,  340,  344,  341,  352,  342,  343,  353,  345,
      354,  346,  355,  357,  347,  348,  349,  358,  359,  350,

      360,  361,  362,  363,  351,  364,  365,  344,  366,  352,
      367,  368,  353,  345,  354,  346,  355,  357,  369,  370,
      371,  358,  359,  372,  360,  361,  362,  363,  373,  364,
      365,  374,  366,  375,  367,  368,  376,  377,  378,  379,
      380,  381,  369,  370,  371,  382,  383,  372,  384,  385,
      386,  387,  373,  388,  389,  374,  390,  375,  391,  392,
      376,  377,  378,  379,  380,  381,  392,  392,  392,  382,
      383,  392,  384,  385,  386,  387,  392,  388,  389,  392,
      390,  392,  391,   33,   33,    3,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,

      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392
    } ;

static yyconst flex_int16_t yy_chk[844] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    7,    7,    9,
        9,   10,   10,   10,   11,   12,   13,   14,   15,   27,
       16,  395,   13,   16,   17,   12,   28,   18,   17,   14,
       18,  393,   14,   30,   33,   33,   24,   12,   11,   12,
       13,   14,   15,   27,   16,   24,   13,   16,   17,   12,

       28,   18,   17,   14,   18,   19,   14,   30,   19,   21,
       24,   12,   19,   21,   19,  243,  243,   21,   22,   24,
       39,   40,   21,  336,   25,   22,   25,   22,  288,   19,
       29,  208,   19,   21,   29,   25,   19,   21,   19,   20,
       20,   21,   22,   20,   39,   40,   21,   20,   25,   22,
       25,   22,   20,  110,   29,   38,   38,   38,   29,   25,
       41,   91,   42,   20,   20,   26,   31,   20,    5,   43,
       44,   20,   45,   26,   46,   47,   20,   23,   48,   49,
       26,   23,   51,   52,   41,   23,   42,   26,   53,   26,
       23,   54,   23,   43,   44,   55,   45,   26,   46,   47,

       56,   23,   48,   49,   26,   23,   51,   52,   57,   23,
       58,   26,   53,   59,   23,   54,   23,   60,   59,   55,
       61,   62,   63,   64,   56,   65,   66,   67,   68,    3,
       71,   63,   57,   72,   58,   73,    0,   59,   74,   75,
       77,   60,   59,   78,   61,   62,   63,   64,   80,   65,
       66,   67,   68,   70,   71,   63,   76,   72,   76,   73,
       70,   79,   74,   75,   77,   81,   70,   78,   82,   83,
       76,   79,   80,   84,   79,   85,   86,   70,   87,   88,
       76,   90,   76,   92,   70,   79,   93,   94,   89,   81,
       70,   95,   82,   83,   76,   79,   96,   84,   79,   85,

       86,   97,   87,   88,   89,   90,   98,   92,   99,  100,
       93,   94,   89,  101,  102,   95,  103,  105,  107,  108,
       96,  109,  111,   97,  112,   97,  113,  114,   89,  115,
       98,  116,   99,  100,  117,  118,  119,  101,  102,  121,
      103,  105,  107,  108,  123,  109,  111,  124,  112,  125,
      113,  114,  126,  115,  127,  116,  128,  129,  117,  118,
      119,  130,  131,  121,  129,  132,  133,  134,  123,  135,
      136,  124,  137,  125,  138,  139,  126,  140,  127,  141,
      128,  129,  142,  143,  144,  130,  131,  145,  129,  132,
      133,  134,  146,  135,  136,  149,  137,  150,  138,  139,

      151,  140,  152,  141,  153,  155,  142,  143,  144,  157,
      156,  145,  158,  159,  160,  161,  146,  162,  163,  149,
      164,  150,  156,  165,  151,  167,  152,  168,  153,  155,
      169,  170,  172,  157,  156,  174,  158,  159,  160,  161,
      175,  162,  163,  176,  164,  178,  156,  165,  179,  167,
      180,  168,  181,  183,  169,  170,  172,  184,  185,  174,
      186,  187,  188,  189,  175,  189,  190,  176,  191,  178,
      192,  193,  179,  194,  180,  195,  181,  183,  198,  199,
      200,  184,  185,  201,  186,  187,  188,  189,  202,  189,
      190,  203,  191,  204,  192,  193,  206,  194,  207,  195,

      209,  210,  198,  199,  200,  211,  212,  201,  215,  216,
      217,  218,  202,  220,  221,  203,  222,  204,  223,  224,
      206,  225,  207,  226,  209,  210,  227,  228,  229,  211,
      212,  230,  215,  216,  217,  218,  231,  220,  221,  232,
      222,  233,  223,  224,  234,  225,  235,  226,  237,  238,
      227,  228,  229,  239,  240,  230,  241,  242,  244,  245,
      231,  246,  249,  232,  251,  233,  252,  253,  234,  254,
      235,  256,  237,  238,  257,  255,  258,  239,  240,  260,
      241,  242,  244,  245,  263,  246,  249,  255,  251,  264,
      252,  253,  266,  254,  267,  256,  269,  270,  257,  255,

      258,  272,  273,  260,  274,  275,  276,  277,  263,  278,
      279,  255,  281,  264,  282,  283,  266,  284,  267,  289,
      269,  270,  290,  291,  292,  272,  273,  293,  274,  275,
      276,  277,  295,  278,  279,  296,  281,  297,  282,  283,
      298,  284,  299,  289,  300,  301,  290,  291,  292,  302,
      303,  293,  304,  306,  307,  309,  295,  312,  313,  296,
      314,  297,  315,  319,  298,    0,  299,    0,  300,  301,
      322,  324,  325,  302,  303,  326,  304,  306,  307,  309,
      327,  312,  313,  320,  314,  329,  315,  319,  330,  320,
      333,  320,  335,  340,  322,  324,  325,  342,  344,  326,

      345,  346,  348,  351,  327,  352,  353,  320,  356,  329,
      357,  358,  330,  320,  333,  320,  335,  340,  360,  361,
      362,  342,  344,  364,  345,  346,  348,  351,  365,  352,
      353,  366,  356,  367,  357,  358,  368,  369,  370,  374,
      376,  378,  360,  361,  362,  379,  380,  364,  381,  382,
      383,  385,  365,  386,  387,  366,  388,  367,  390,    0,
      368,  369,  370,  374,  376,  378,    0,    0,    0,  379,
      380,    0,  381,  382,  383,  385,    0,  386,  387,    0,
      388,    0,  390,  394,  394,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,

      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "config-lexer.l"
/*
 *  Copyright (c) 2002 Erik Fears
 *  Copyright (c) 2014-2015 ircd-hybrid development team
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301
 *  USA
 */
#line 27 "config-lexer.l"
#include <stdio.h>
#include <string.h>

#include "compat.h"
#include "config.h"
#include "config-parser.h"


static void ccomment(void);

unsigned int linenum = 1;
char linebuf[512];

#line 808 "config-lexer.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 46 "config-lexer.l"


#line 1018 "config-lexer.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (yy_c_buf_p) - (yytext_ptr);
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 393 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 392 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 48 "config-lexer.l"
{ ccomment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 50 "config-lexer.l"
;
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 52 "config-lexer.l"
{
                           /* QSTRING from Hybrid7. Why re-invent the wheel? */

                           if(yytext[yyleng-2] == '\\')
                           {
                              yyless(yyleng-1); /* return last quote */
                              yymore();         /* append next string */
                           }
                           else
                           {
                              yylval.string = yytext+1;
                              if(yylval.string[yyleng-2] != '"') ; /* log error */
                              else
                              {
                                 int i,j;

                                 yylval.string[yyleng-2] = '\0'; /* remove close
                                                                  *  quote
                                                                  */

                                 for (j=i=0 ;yylval.string[i] != '\0'; i++,j++)
                                 {
                                    if (yylval.string[i] != '\\')
                                    {
                                       yylval.string[j] = yylval.string[i];
                                    }
                                    else
                                    {
                                        i++;
                                        yylval.string[j] = yylval.string[i];
                                    }
                                 }
                                 yylval.string[j] = '\0';
                                 return STRING;
                              }
                           }
                        }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 90 "config-lexer.l"
{ return AWAY;         }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 91 "config-lexer.l"
{ return BAN_UNKNOWN;  }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 92 "config-lexer.l"
{ return BLACKLIST;    }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 93 "config-lexer.l"
{ return CHANNEL;      }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 94 "config-lexer.l"
{ return CONNREGEX;    }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 95 "config-lexer.l"
{ return DNS_FDLIMIT;  }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 96 "config-lexer.l"
{ return DNS_TIMEOUT;  }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 97 "config-lexer.l"
{ return DNSBL_FROM;   }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 98 "config-lexer.l"
{ return DNSBL_TO;     }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 99 "config-lexer.l"
{ return EXEMPT;       }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 100 "config-lexer.l"
{ return FD;           }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 101 "config-lexer.l"
{ return INVITE;       }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 102 "config-lexer.l"
{ return IRC;          }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 103 "config-lexer.l"
{ return KLINE;        }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 104 "config-lexer.l"
{ return KEY;          }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 105 "config-lexer.l"
{ return MASK;         }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 106 "config-lexer.l"
{ return MAX_READ;     }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 107 "config-lexer.l"
{ return MODE;         }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 108 "config-lexer.l"
{ return NAME;         }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 109 "config-lexer.l"
{ return NEGCACHE;     }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 110 "config-lexer.l"
{ return NEGCACHE_REBUILD; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 111 "config-lexer.l"
{ return NICK;         }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 112 "config-lexer.l"
{ return NICKSERV;     }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 113 "config-lexer.l"
{ return NOTICE;       }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 114 "config-lexer.l"
{ return OPER;         }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 115 "config-lexer.l"
{ return OPM;          }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 116 "config-lexer.l"
{ return OPTIONS;      }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 117 "config-lexer.l"
{ return PASSWORD;     }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 118 "config-lexer.l"
{ return PERFORM;      }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 119 "config-lexer.l"
{ return PIDFILE;      }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 120 "config-lexer.l"
{ return PORT;         }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 121 "config-lexer.l"
{ return PROTOCOL;     }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 122 "config-lexer.l"
{ return READTIMEOUT;  }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 123 "config-lexer.l"
{ return REALNAME;     }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 124 "config-lexer.l"
{ return RECONNECTINTERVAL; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 125 "config-lexer.l"
{ return REPLY;        }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 126 "config-lexer.l"
{ return SCANLOG;      }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 127 "config-lexer.l"
{ return SCANNER;      }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 128 "config-lexer.l"
{ return SENDMAIL;     }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 129 "config-lexer.l"
{ return SERVER;       }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 130 "config-lexer.l"
{ return TARGET_IP;    }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 131 "config-lexer.l"
{ return TARGET_PORT;  }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 132 "config-lexer.l"
{ return TARGET_STRING;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 133 "config-lexer.l"
{ return TIMEOUT;      }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 134 "config-lexer.l"
{ return TYPE;         }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 135 "config-lexer.l"
{ return USER;         }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 136 "config-lexer.l"
{ return USERNAME;     }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 137 "config-lexer.l"
{ return VHOST;        }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 139 "config-lexer.l"
{ return YEARS; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 140 "config-lexer.l"
{ return YEARS; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 141 "config-lexer.l"
{ return MONTHS; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 142 "config-lexer.l"
{ return MONTHS; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 143 "config-lexer.l"
{ return WEEKS; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 144 "config-lexer.l"
{ return WEEKS; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 145 "config-lexer.l"
{ return DAYS; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 146 "config-lexer.l"
{ return DAYS; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 147 "config-lexer.l"
{ return HOURS; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 148 "config-lexer.l"
{ return HOURS; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 149 "config-lexer.l"
{ return MINUTES; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 150 "config-lexer.l"
{ return MINUTES; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 151 "config-lexer.l"
{ return SECONDS; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 152 "config-lexer.l"
{ return SECONDS; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 154 "config-lexer.l"
{ return BYTES; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 155 "config-lexer.l"
{ return BYTES; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 156 "config-lexer.l"
{ return KBYTES; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 157 "config-lexer.l"
{ return KBYTES; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 158 "config-lexer.l"
{ return KBYTES; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 159 "config-lexer.l"
{ return KBYTES; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 160 "config-lexer.l"
{ return KBYTES; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 161 "config-lexer.l"
{ return MBYTES; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 162 "config-lexer.l"
{ return MBYTES; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 163 "config-lexer.l"
{ return MBYTES; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 164 "config-lexer.l"
{ return MBYTES; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 165 "config-lexer.l"
{ return MBYTES; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 167 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_HTTP;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 172 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_HTTPPOST;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 177 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_SOCKS4;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 182 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_SOCKS5;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 187 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_WINGATE;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 192 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_ROUTER;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 197 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_DREAMBOX;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 204 "config-lexer.l"
{
                           yylval.number=atoi(yytext);
                           return NUMBER;
                        }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 213 "config-lexer.l"
{
                           yylval.number=1;
                           return NUMBER;
                         }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 217 "config-lexer.l"
{
                           yylval.number=1;
                           return NUMBER;
                         }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 221 "config-lexer.l"
{
                           yylval.number=1;
                           return NUMBER;
                         }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 228 "config-lexer.l"
{
                           yylval.number=0;
                           return NUMBER;
                         }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 233 "config-lexer.l"
{
                           yylval.number=0;
                           return NUMBER;
                         }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 238 "config-lexer.l"
{
                           yylval.number=0;
                           return NUMBER;
                         }
	YY_BREAK
case 92:
/* rule 92 can match eol */
YY_RULE_SETUP
#line 244 "config-lexer.l"
{
                           strlcpy(linebuf, yytext + 1, sizeof(linebuf));
                           ++linenum;
                           yyless(1);
                         }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 250 "config-lexer.l"
/* ignore whitespace */;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 252 "config-lexer.l"
return yytext[0];
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 254 "config-lexer.l"
ECHO;
	YY_BREAK
#line 1636 "config-lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 393 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 393 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 392);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 254 "config-lexer.l"




/* C-comment ignoring routine -kre*/
static void
ccomment(void)
{
  int c = 0;

  /* log(L_NOTICE, "got comment"); */
  while (1)
  {
    while ((c = input()) != '*' && c != EOF)
      if (c == '\n')
        ++linenum;

    if (c == '*')
    {
      while ((c = input()) == '*')
        /* Nothing */ ;
      if (c == '/')
        break;
      else if (c == '\n')
        ++linenum;
    }

    if (c == EOF)
    {
      YY_FATAL_ERROR("EOF in comment");

      /* XXX hack alert this disables
       * the stupid unused function warning
       * gcc generates
       */
      if (1 == 0)
        yy_fatal_error("EOF in comment");
      break;
    }
  }
}

