
#line 3 "config-lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (int) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 112
#define YY_END_OF_BUFFER 113
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[526] =
    {   0,
        7,    7,    0,    0,  113,  111,    7,    6,  111,    8,
      111,  111,    9,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,    3,    4,    3,    7,    6,    0,   10,    8,
        0,    1,    8,    9,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   26,    0,    0,
        0,    0,    0,   89,    0,    0,    0,    0,   94,    0,
        0,    0,    0,    0,    0,  109,    0,  107,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        2,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   76,    0,    0,    0,    0,    0,    0,    0,    0,
       30,    0,   32,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  110,    0,   43,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  104,    0,    0,   63,    0,
        0,    0,    0,    0,    0,  106,    0,    0,   12,    0,
       14,    0,   84,    0,    0,    0,   75,    0,    0,    0,
        0,    0,   78,   95,    0,   28,   29,    0,    0,    0,
       33,    0,    0,    0,    0,   35,    0,   36,    0,   39,

        0,   42,    0,    0,    0,    0,   48,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  105,   66,   67,   74,    0,   70,    0,    0,
        0,    0,   83,    0,    0,    0,    0,    0,    0,    0,
        0,  108,   77,    0,   97,    0,   88,    0,   31,    0,
       93,    0,    0,   72,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   53,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   73,
        0,   69,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   25,    0,    0,   27,   87,    0,    0,

       92,    0,   80,   71,    0,    0,   41,    0,    0,    0,
        0,    0,    0,    0,    0,  102,    0,    0,    0,   82,
        0,   58,   99,  100,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   16,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   79,    0,    0,
       44,    0,   46,   47,    0,    0,    0,    0,    0,   55,
       56,   81,    0,    0,   62,    0,    0,    0,  101,    0,
        0,    0,    0,    0,    0,    0,   24,    0,    0,  103,
       96,    0,   86,   34,   91,   37,   40,   45,   49,    0,
       51,    0,    0,   57,    0,    0,    0,    0,    0,   68,

        0,    0,    0,    0,    0,   15,    0,    0,    0,   20,
        0,    0,    0,   98,   85,   90,    0,    0,    0,    0,
       59,    0,    0,    0,    0,    0,    5,    0,    5,    0,
        0,    0,    0,    0,   23,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   13,    0,    0,    0,
       21,   22,    0,   50,    0,    0,   60,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   61,    0,    0,
       11,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   19,    0,    0,    0,    0,    0,   17,    0,   38,

        0,    0,    0,    0,    0,   52,    0,    0,    0,   18,
        0,    0,    0,    0,    0,    0,   54,   64,    0,    0,
        0,    0,    0,   65,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    1,
        1,    6,    1,    1,    1,    7,    8,    9,    9,    9,
        9,   10,   11,   12,    9,    9,    9,    1,    1,   13,
        1,   14,    1,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,    1,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
        1,    1,    1,    1,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,    1,   50,   51,   52,   53,
       54,   55,   56,   57,   58,   59,   60,   61,   62,   63,
       64,   65,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[66] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[532] =
    {   0,
        0,    0,   63,   64, 1026, 1038, 1023,    0,   68,    0,
       45,   67,   67,   56,   65,   59,   68,   45,   71,   63,
       97,  111,  148,  116,  113,  188,   65,  155,  231,   53,
      124,  101, 1038, 1038, 1016, 1020,    0,   98, 1038,    0,
      105, 1038,    0,  168,  131,  140,  155,  157,  171,  155,
      176,  168,  154,  164,  180,  182,  179, 1038,  171,  173,
      180,  188,  207,  188,  196,  210,  215,  207,  202,  226,
      221,  240,  225,  232,  238,  224,  239, 1038,  268,  231,
      240,  258,  247,  258,  281,  256,  276,  277,  288,  282,
      278,  272,  280,  275,  274,  280,  292,  295,  294,  323,

     1038,  306,  297,  292,  981,  321,  325,  324,  317,  320,
      321,  318,  335,  337,  327,  325,  327,  330,  337,  351,
     1038,  329, 1038,  338,  340,  347,  980,  340,  365,  348,
      368,  356,  371,  374,  370,  372, 1038,  365, 1038,  375,
      368,  381,  382,  370,  371,  387,  379,  384,  377,  979,
      384,  386,  400,  384,  399, 1038,  404,  413,  978,  415,
      420,  410,  418,  422,  415, 1038,  422,  429, 1038,  416,
     1038,  428,  421,  427,  440,  425, 1038,  432,  442,  433,
      432,  444,  432,  462,  433, 1038, 1038,  451,  455,  458,
     1038,  453,  467,  477,  462, 1038,  476, 1038,  484,  468,

      485, 1038,  476,  469,  478,  484, 1038,  480,  476,  484,
      486,  476,  496,  487,  502,  491,  496,  504,  504,  519,
      515,  528, 1038, 1038,  519,  515,  536,  520,  520,  524,
      530,  533, 1038,  540,  533,  542,  976,  545,  542,  550,
      534, 1038, 1038,  540,  541,  555,  543,  541, 1038,  562,
      556,  552,  576,  565,  581,  580,  583,  576,  576,  575,
      583,  592,  587,  596,  585, 1038,  582,  584,  589,  599,
      601,  605,  591,   94,  593,  593,  612,  605,  625, 1038,
      609, 1038,  629,  617,  626,  628,  629,  637,  635,  638,
      635,  635,  634, 1038,  631,  636, 1038, 1038,  632,  652,

     1038,  636,  638, 1038,  650,  643, 1038,  646,  648,  657,
      666,  664,  668,  673,  682, 1038,  679,  682,  675,  675,
      685, 1038, 1038, 1038,  975,  677,  681,  681,  688,  696,
      697,  974,  690,  687, 1038,  973,  702,  691,  695,  701,
      707,  693,  698,  703,  718,  726,  727, 1038,  732,  718,
     1038,  736, 1038, 1038,  730,  739,  740,  743,  727, 1038,
     1038, 1038,  739,  742, 1038,  733,  734,  749, 1038,  774,
      749,  745,  742,  773,  745,  755, 1038,  763,  770, 1038,
     1038,  769,  772, 1038,  773,  972, 1038, 1038, 1038,  779,
     1038,  777,  796, 1038,  783,  785,  781,  793,  790, 1038,

      821, 1007,  996,  803,  783, 1038,  793,  787,  803, 1038,
      801,  812,  807, 1038, 1038, 1038,  817,  815,  827,  818,
     1038,  823,  824,  836,  842,  271,  264,  229,  222,  832,
      832,  827,  843,  837, 1038,  831,  832,  847,  835,  842,
      851,  838,  849,  850,  852,  856, 1038,  868,  859,  881,
     1038, 1038,  885, 1038,  869,  188, 1038,  876,  889,  888,
      883,  878,  891,  883,  878,  895,  891,  895,  902,  145,
      880,  885,  111,  887,  899,  892,  905, 1038,  892,  895,
     1038,  916,  907,  912,  927,  918,  916,  936,  939,  934,
      937, 1038,  943,  947,  108,  105,  932, 1038,  925, 1038,

      941,  947,  948,  946,  951, 1038,  949,  950,  954, 1038,
      950,  951,  954,  963,  964,  974, 1038, 1038,  982,  971,
      982,  978,  980, 1038, 1038, 1033,  140, 1035,  137,  136,
       97
    } ;

static const flex_int16_t yy_def[532] =
    {   0,
      525,    1,  526,  526,  525,  525,  525,  527,  528,  529,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  527,  528,  525,  529,
      525,  525,  529,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,

      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,

      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,

      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,

      525,  530,  531,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  530,  530,  531,  531,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,

      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,    0,  525,  525,  525,  525,  525,
      525
    } ;

static const flex_int16_t yy_nxt[1104] =
    {   0,
        6,    7,    8,    9,   10,    6,   11,   12,   13,   13,
       13,   13,    6,    6,   14,   15,   16,   17,   18,   19,
        6,   20,   21,   22,    6,   23,   24,   25,   26,    6,
       27,   28,   29,   30,    6,   31,    6,   32,    6,    6,
       14,   15,   16,   17,   18,   19,    6,   20,   21,   22,
        6,   23,   24,   25,   26,    6,   27,   28,   29,   30,
        6,   31,    6,   32,    6,   34,   34,   41,   35,   35,
       39,   39,   42,   45,   43,   44,   44,   44,   44,   47,
       51,   56,   53,   85,   97,   57,   52,   48,   58,   49,
       59,   46,   86,   41,   54,   60,   87,  428,   55,   45,

       39,   39,   50,  323,  324,   47,   51,   56,   53,   85,
       97,   57,   52,   48,   58,   49,   59,   46,   86,  100,
       54,   60,   87,   61,   55,   62,   64,   63,   50,   65,
       73,  102,   77,   66,   74,   67,  426,   40,   75,   78,
       37,   79,   98,   76,  503,  100,   99,  502,  103,   61,
      483,   62,   64,   63,  104,   65,   73,  102,   77,   66,
       74,   67,   68,   69,   75,   78,   70,   79,   98,   76,
       71,   88,   99,   89,  103,   72,   44,   44,   44,   44,
      104,  105,   90,  106,  480,  107,   91,  108,   68,   69,
      109,  112,   70,  110,  111,  113,   71,   88,  114,   89,

      115,   72,   80,  116,  117,  118,   81,  105,   90,  106,
       82,  107,   91,  108,  119,   83,  109,  112,   84,  110,
      111,  113,  120,  121,  114,  122,  115,  467,   80,  116,
      117,  118,   81,  123,  124,  429,   82,  125,  126,  128,
      119,   83,  429,  127,   84,   92,  129,  130,  120,  121,
      133,  122,  134,   93,  135,   94,  136,  131,  137,  123,
      124,   95,  141,  125,  126,  128,  132,  427,   96,  127,
      142,   92,  129,  130,  427,  143,  133,  144,  134,   93,
      135,   94,  136,  131,  137,  145,  138,   95,  141,  149,
      150,  151,  132,  139,   96,  146,  142,  147,  155,  156,

      140,  143,  157,  144,  152,  158,  159,  160,  161,  148,
      162,  145,  138,  163,  153,  149,  150,  151,  154,  139,
      164,  146,  167,  147,  155,  156,  140,  168,  157,  169,
      152,  158,  159,  160,  161,  148,  162,  165,  171,  163,
      153,  172,  173,  174,  154,  175,  164,  176,  167,  177,
      178,  180,  181,  168,  166,  169,  182,  183,  184,  185,
      186,  188,  187,  165,  171,  189,  190,  172,  173,  174,
      191,  175,  193,  176,  179,  177,  178,  180,  181,  194,
      166,  195,  182,  183,  184,  185,  196,  188,  197,  198,
      199,  189,  190,  200,  201,  202,  191,  203,  193,  204,

      205,  206,  207,  208,  209,  194,  211,  195,  212,  213,
      215,  210,  196,  216,  197,  198,  199,  217,  218,  200,
      201,  202,  219,  203,  220,  204,  205,  206,  207,  208,
      209,  221,  211,  223,  212,  213,  215,  210,  224,  216,
      225,  226,  227,  217,  218,  228,  229,  230,  219,  231,
      220,  232,  233,  234,  235,  236,  237,  221,  240,  223,
      241,  238,  242,  243,  224,  246,  225,  226,  227,  247,
      248,  228,  229,  230,  239,  231,  249,  232,  233,  234,
      235,  236,  237,  250,  240,  251,  241,  238,  242,  243,
      244,  246,  252,  245,  253,  247,  248,  254,  255,  256,

      239,  257,  249,  258,  259,  260,  261,  262,  263,  250,
      264,  251,  265,  266,  267,  268,  244,  271,  252,  245,
      253,  272,  273,  254,  255,  256,  269,  257,  270,  258,
      259,  260,  261,  262,  263,  274,  264,  275,  265,  266,
      267,  268,  276,  271,  277,  279,  280,  272,  273,  278,
      281,  282,  269,  283,  270,  284,  285,  286,  287,  288,
      289,  274,  291,  275,  292,  293,  294,  295,  276,  296,
      277,  279,  280,  297,  298,  278,  281,  282,  299,  283,
      300,  284,  285,  286,  287,  288,  289,  301,  291,  302,
      292,  293,  294,  295,  303,  296,  304,  305,  306,  297,

      298,  307,  308,  309,  299,  310,  300,  311,  312,  313,
      314,  315,  316,  301,  317,  302,  318,  319,  320,  321,
      303,  322,  304,  305,  306,  325,  326,  307,  308,  309,
      327,  310,  328,  311,  312,  313,  314,  315,  316,  329,
      317,  330,  318,  319,  320,  321,  331,  322,  332,  333,
      334,  325,  326,  335,  336,  337,  327,  338,  328,  340,
      341,  342,  343,  344,  345,  329,  346,  330,  347,  348,
      339,  349,  331,  350,  332,  333,  334,  351,  352,  335,
      336,  337,  353,  338,  354,  340,  341,  342,  343,  344,
      345,  355,  346,  356,  347,  348,  339,  349,  357,  350,

      358,  359,  360,  351,  352,  361,  362,  363,  353,  365,
      354,  366,  367,  368,  369,  370,  372,  355,  373,  356,
      375,  376,  377,  378,  357,  379,  358,  359,  360,  380,
      381,  361,  362,  363,  382,  365,  383,  366,  367,  368,
      369,  370,  372,  384,  373,  385,  375,  376,  377,  378,
      386,  379,  387,  388,  389,  380,  381,  390,  391,  392,
      382,  393,  383,  394,  395,  398,  399,  400,  404,  384,
      396,  385,  405,  397,  406,  401,  386,  402,  387,  388,
      389,  410,  411,  390,  391,  392,  403,  393,  412,  394,
      395,  398,  399,  400,  404,  407,  396,  413,  405,  397,

      406,  414,  408,  415,  416,  409,  418,  410,  411,  419,
      420,  421,  422,  423,  412,  424,  425,  430,  431,  432,
      433,  407,  401,  413,  402,  434,  435,  414,  408,  415,
      416,  409,  418,  403,  436,  419,  420,  421,  422,  423,
      437,  424,  425,  430,  431,  432,  433,  438,  439,  440,
      441,  434,  435,  442,  443,  444,  445,  446,  447,  448,
      436,  449,  450,  451,  452,  453,  437,  454,  455,  456,
      457,  458,  459,  438,  439,  440,  441,  460,  461,  442,
      443,  444,  445,  446,  447,  448,  462,  449,  450,  451,
      452,  453,  463,  454,  455,  456,  457,  458,  459,  464,

      465,  466,  468,  460,  461,  469,  470,  471,  472,  473,
      474,  475,  462,  476,  477,  478,  479,  481,  463,  482,
      484,  485,  486,  487,  488,  464,  465,  466,  468,  489,
      490,  469,  470,  471,  472,  473,  474,  475,  491,  476,
      477,  478,  479,  481,  492,  482,  484,  485,  486,  487,
      488,  493,  494,  495,  496,  489,  490,  497,  498,  499,
      500,  501,  504,  505,  491,  506,  507,  508,  509,  510,
      492,  511,  512,  513,  514,  515,  516,  493,  494,  495,
      496,  517,  518,  497,  498,  499,  500,  501,  504,  505,
      519,  506,  507,  508,  509,  510,  520,  511,  512,  513,

      514,  515,  516,  521,  522,  523,  524,  517,  518,  429,
      427,  417,  374,  371,  364,  290,  519,  222,  214,  192,
      170,   36,  520,  101,   36,  525,  525,  525,  525,  521,
      522,  523,  524,   33,   33,   38,   38,    5,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,

      525,  525,  525
    } ;

static const flex_int16_t yy_chk[1104] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,   11,    3,    4,
        9,    9,   12,   14,   12,   13,   13,   13,   13,   15,
       16,   18,   17,   27,   30,   19,   16,   15,   19,   15,
       20,   14,   27,   11,   17,   20,   27,  531,   17,   14,

       38,   38,   15,  274,  274,   15,   16,   18,   17,   27,
       30,   19,   16,   15,   19,   15,   20,   14,   27,   32,
       17,   20,   27,   21,   17,   21,   22,   21,   15,   22,
       24,   41,   25,   22,   24,   22,  530,  529,   24,   25,
      527,   25,   31,   24,  496,   32,   31,  495,   45,   21,
      473,   21,   22,   21,   46,   22,   24,   41,   25,   22,
       24,   22,   23,   23,   24,   25,   23,   25,   31,   24,
       23,   28,   31,   28,   45,   23,   44,   44,   44,   44,
       46,   47,   28,   48,  470,   49,   28,   50,   23,   23,
       51,   53,   23,   52,   52,   54,   23,   28,   55,   28,

       56,   23,   26,   57,   59,   60,   26,   47,   28,   48,
       26,   49,   28,   50,   61,   26,   51,   53,   26,   52,
       52,   54,   62,   63,   55,   64,   56,  456,   26,   57,
       59,   60,   26,   65,   66,  429,   26,   67,   68,   69,
       61,   26,  428,   68,   26,   29,   70,   71,   62,   63,
       73,   64,   74,   29,   75,   29,   76,   72,   77,   65,
       66,   29,   80,   67,   68,   69,   72,  427,   29,   68,
       81,   29,   70,   71,  426,   82,   73,   83,   74,   29,
       75,   29,   76,   72,   77,   84,   79,   29,   80,   86,
       87,   88,   72,   79,   29,   85,   81,   85,   90,   91,

       79,   82,   92,   83,   89,   93,   94,   95,   96,   85,
       97,   84,   79,   98,   89,   86,   87,   88,   89,   79,
       99,   85,  102,   85,   90,   91,   79,  103,   92,  104,
       89,   93,   94,   95,   96,   85,   97,  100,  106,   98,
       89,  107,  108,  109,   89,  110,   99,  111,  102,  112,
      113,  114,  115,  103,  100,  104,  116,  117,  118,  119,
      120,  122,  120,  100,  106,  124,  125,  107,  108,  109,
      126,  110,  128,  111,  113,  112,  113,  114,  115,  129,
      100,  130,  116,  117,  118,  119,  131,  122,  132,  133,
      134,  124,  125,  135,  136,  138,  126,  140,  128,  141,

      142,  143,  144,  145,  146,  129,  147,  130,  148,  149,
      151,  146,  131,  152,  132,  133,  134,  153,  154,  135,
      136,  138,  155,  140,  157,  141,  142,  143,  144,  145,
      146,  158,  147,  160,  148,  149,  151,  146,  161,  152,
      162,  163,  164,  153,  154,  165,  167,  168,  155,  170,
      157,  172,  173,  174,  175,  176,  178,  158,  180,  160,
      181,  179,  182,  183,  161,  185,  162,  163,  164,  188,
      189,  165,  167,  168,  179,  170,  190,  172,  173,  174,
      175,  176,  178,  192,  180,  193,  181,  179,  182,  183,
      184,  185,  194,  184,  195,  188,  189,  197,  199,  200,

      179,  201,  190,  203,  204,  205,  206,  208,  209,  192,
      210,  193,  211,  212,  213,  214,  184,  216,  194,  184,
      195,  217,  218,  197,  199,  200,  215,  201,  215,  203,
      204,  205,  206,  208,  209,  219,  210,  220,  211,  212,
      213,  214,  221,  216,  222,  225,  226,  217,  218,  222,
      227,  228,  215,  229,  215,  230,  231,  232,  234,  235,
      236,  219,  238,  220,  239,  240,  241,  244,  221,  245,
      222,  225,  226,  246,  247,  222,  227,  228,  248,  229,
      250,  230,  231,  232,  234,  235,  236,  251,  238,  252,
      239,  240,  241,  244,  253,  245,  254,  255,  256,  246,

      247,  257,  258,  259,  248,  260,  250,  261,  262,  263,
      264,  265,  267,  251,  268,  252,  269,  270,  271,  272,
      253,  273,  254,  255,  256,  275,  276,  257,  258,  259,
      277,  260,  278,  261,  262,  263,  264,  265,  267,  279,
      268,  281,  269,  270,  271,  272,  283,  273,  284,  285,
      286,  275,  276,  287,  288,  289,  277,  290,  278,  291,
      292,  293,  295,  296,  299,  279,  300,  281,  302,  303,
      290,  305,  283,  306,  284,  285,  286,  308,  309,  287,
      288,  289,  310,  290,  311,  291,  292,  293,  295,  296,
      299,  312,  300,  313,  302,  303,  290,  305,  314,  306,

      315,  317,  318,  308,  309,  319,  320,  321,  310,  326,
      311,  327,  328,  329,  330,  331,  333,  312,  334,  313,
      337,  338,  339,  340,  314,  341,  315,  317,  318,  342,
      343,  319,  320,  321,  344,  326,  345,  327,  328,  329,
      330,  331,  333,  346,  334,  347,  337,  338,  339,  340,
      349,  341,  350,  352,  355,  342,  343,  356,  357,  358,
      344,  359,  345,  363,  364,  366,  367,  368,  371,  346,
      364,  347,  372,  364,  373,  370,  349,  370,  350,  352,
      355,  375,  376,  356,  357,  358,  370,  359,  378,  363,
      364,  366,  367,  368,  371,  374,  364,  379,  372,  364,

      373,  382,  374,  383,  385,  374,  390,  375,  376,  392,
      393,  395,  396,  397,  378,  398,  399,  404,  405,  407,
      408,  374,  401,  379,  401,  409,  411,  382,  374,  383,
      385,  374,  390,  401,  412,  392,  393,  395,  396,  397,
      413,  398,  399,  404,  405,  407,  408,  417,  418,  419,
      420,  409,  411,  422,  423,  424,  425,  430,  431,  432,
      412,  433,  434,  436,  437,  438,  413,  439,  440,  441,
      442,  443,  444,  417,  418,  419,  420,  445,  446,  422,
      423,  424,  425,  430,  431,  432,  448,  433,  434,  436,
      437,  438,  449,  439,  440,  441,  442,  443,  444,  450,

      453,  455,  458,  445,  446,  459,  460,  461,  462,  463,
      464,  465,  448,  466,  467,  468,  469,  471,  449,  472,
      474,  475,  476,  477,  479,  450,  453,  455,  458,  480,
      482,  459,  460,  461,  462,  463,  464,  465,  483,  466,
      467,  468,  469,  471,  484,  472,  474,  475,  476,  477,
      479,  485,  486,  487,  488,  480,  482,  489,  490,  491,
      493,  494,  497,  499,  483,  501,  502,  503,  504,  505,
      484,  507,  508,  509,  511,  512,  513,  485,  486,  487,
      488,  514,  515,  489,  490,  491,  493,  494,  497,  499,
      516,  501,  502,  503,  504,  505,  519,  507,  508,  509,

      511,  512,  513,  520,  521,  522,  523,  514,  515,  403,
      402,  386,  336,  332,  325,  237,  516,  159,  150,  127,
      105,   36,  519,   35,    7,    5,    0,    0,    0,  520,
      521,  522,  523,  526,  526,  528,  528,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,

      525,  525,  525
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "config-lexer.l"
/*
 *  Copyright (c) 2002 Erik Fears
 *  Copyright (c) 2014-2021 ircd-hybrid development team
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301
 *  USA
 */
#define YY_NO_INPUT 1

#line 30 "config-lexer.l"
#include <stdio.h>
#include <string.h>

#include "compat.h"
#include "config.h"
#include "config-parser.h"  /* autogenerated header file */
#include "log.h"

/* libopm includes */
#include "libopm/src/opm_types.h"

#undef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) conf_yy_fatal_error(msg)

#undef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
  if (!(result = conf_yy_input(buf, max_size))) \
    YY_FATAL_ERROR("input in flex scanner failed");
#define MAX_INCLUDE_DEPTH 10


unsigned int lineno = 1;
char linebuf[512];
char conffilebuf[512];

static struct included_file
{
  YY_BUFFER_STATE state;
  unsigned int lineno;
  FILE *file;
  char conffile[512];
} include_stack[MAX_INCLUDE_DEPTH];

static unsigned int include_stack_ptr;


static void conf_include(void);
static int conf_eof(void);

static int
conf_yy_input(char *lbuf, unsigned int max_size)
{
  return fgets(lbuf, max_size, conf_file) == NULL ? 0 : strlen(lbuf);
}

static int
conf_yy_fatal_error(const char *msg)
{
  return 0;
}
#line 940 "config-lexer.c"
#line 941 "config-lexer.c"

#define INITIAL 0
#define IN_COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 88 "config-lexer.l"


#line 1160 "config-lexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (int) ((yy_c_buf_p) - (yytext_ptr));
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 526 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 525 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 90 "config-lexer.l"
{ BEGIN IN_COMMENT; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 91 "config-lexer.l"
{ BEGIN INITIAL;    }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 92 "config-lexer.l"
;  /* Eat everything but a newline */
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 93 "config-lexer.l"
{ ++lineno; }
	YY_BREAK
case YY_STATE_EOF(IN_COMMENT):
#line 94 "config-lexer.l"
{ BEGIN INITIAL; if (conf_eof()) yyterminate(); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 96 "config-lexer.l"
{ conf_include(); }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 97 "config-lexer.l"
{ strlcpy(linebuf, yytext + 1, sizeof(linebuf)); ++lineno; yyless(1); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 98 "config-lexer.l"
;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 99 "config-lexer.l"
;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 100 "config-lexer.l"
{ yylval.number = atoi(yytext); return NUMBER; }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 101 "config-lexer.l"
{ if (yytext[yyleng - 2] == '\\')
                  {
                    yyless(yyleng - 1);  /* Return last quote */
                    yymore();  /* Append next string */
                  }
                  else
                  {
                    yylval.string = yytext + 1;

                    if (yylval.string[yyleng - 2] != '"')
                      log_printf("CONFIG ->Unterminated character string");
                    else
                    {
                      unsigned int i = 0, j = 0;

                      yylval.string[yyleng - 2] = '\0';  /* Remove close quote */

                      for (; yylval.string[i] != '\0'; ++i, ++j)
                      {
                        if (yylval.string[i] != '\\')
                          yylval.string[j] = yylval.string[i];
                        else
                        {
                          ++i;

                          if (yylval.string[i] == '\0')  /* XXX: should not happen */
                          {
                            log_printf("CONFIG -> Unterminated character string");
                            break;
                          }

                          yylval.string[j] = yylval.string[i];
                        }
                      }

                      yylval.string[j] = '\0';
                      return STRING;
                    }
                  }
                }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 142 "config-lexer.l"
{ return ADDRESS_FAMILY; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 143 "config-lexer.l"
{ return AWAY;         }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 144 "config-lexer.l"
{ return BAN_UNKNOWN;  }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 145 "config-lexer.l"
{ return BIND;         }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 146 "config-lexer.l"
{ return BLACKLIST;    }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 147 "config-lexer.l"
{ return CHANNEL;      }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 148 "config-lexer.l"
{ return COMMAND_INTERVAL; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 149 "config-lexer.l"
{ return COMMAND_QUEUE_SIZE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 150 "config-lexer.l"
{ return COMMAND_TIMEOUT; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 151 "config-lexer.l"
{ return CONNREGEX;    }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 152 "config-lexer.l"
{ return DNS_FDLIMIT;  }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 153 "config-lexer.l"
{ return DNS_TIMEOUT;  }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 154 "config-lexer.l"
{ return DNSBL_FROM;   }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 155 "config-lexer.l"
{ return DNSBL_TO;     }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 156 "config-lexer.l"
{ return EXEMPT;       }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 157 "config-lexer.l"
{ return FD;           }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 158 "config-lexer.l"
{ return INVITE;       }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 159 "config-lexer.l"
{ return IPV4;         }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 160 "config-lexer.l"
{ return IPV6;         }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 161 "config-lexer.l"
{ return IRC;          }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 162 "config-lexer.l"
{ return KLINE;        }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 163 "config-lexer.l"
{ return KEY;          }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 164 "config-lexer.l"
{ return MASK;         }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 165 "config-lexer.l"
{ return MAX_READ;     }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 166 "config-lexer.l"
{ return MODE;         }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 167 "config-lexer.l"
{ return NAME;         }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 168 "config-lexer.l"
{ return NEGCACHE;     }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 169 "config-lexer.l"
{ return NEGCACHE_REBUILD; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 170 "config-lexer.l"
{ return NICK;         }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 171 "config-lexer.l"
{ return NICKSERV;     }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 172 "config-lexer.l"
{ return NOTICE;       }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 173 "config-lexer.l"
{ return OPER;         }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 174 "config-lexer.l"
{ return OPM;          }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 175 "config-lexer.l"
{ return OPTIONS;      }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 176 "config-lexer.l"
{ return PASSWORD;     }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 177 "config-lexer.l"
{ return PERFORM;      }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 178 "config-lexer.l"
{ return PIDFILE;      }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 179 "config-lexer.l"
{ return PORT;         }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 180 "config-lexer.l"
{ return PROTOCOL;     }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 181 "config-lexer.l"
{ return READTIMEOUT;  }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 182 "config-lexer.l"
{ return REALNAME;     }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 183 "config-lexer.l"
{ return RECONNECTINTERVAL; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 184 "config-lexer.l"
{ return REPLY;        }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 185 "config-lexer.l"
{ return RSA_PRIVATE_KEY_FILE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 186 "config-lexer.l"
{ return SCANLOG;      }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 187 "config-lexer.l"
{ return SCANNER;      }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 188 "config-lexer.l"
{ return SENDMAIL;     }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 189 "config-lexer.l"
{ return SERVER;       }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 190 "config-lexer.l"
{ return TARGET_IP;    }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 191 "config-lexer.l"
{ return TARGET_PORT;  }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 192 "config-lexer.l"
{ return TARGET_STRING;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 193 "config-lexer.l"
{ return TIMEOUT;      }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 194 "config-lexer.l"
{ return TLS;          }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 195 "config-lexer.l"
{ return TLS_CERTIFICATE_FILE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 196 "config-lexer.l"
{ return TLS_HOSTNAME_VERIFICATION; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 197 "config-lexer.l"
{ return TYPE;         }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 198 "config-lexer.l"
{ return USER;         }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 199 "config-lexer.l"
{ return USERNAME;     }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 201 "config-lexer.l"
{ return YEARS; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 202 "config-lexer.l"
{ return YEARS; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 203 "config-lexer.l"
{ return MONTHS; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 204 "config-lexer.l"
{ return MONTHS; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 205 "config-lexer.l"
{ return WEEKS; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 206 "config-lexer.l"
{ return WEEKS; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 207 "config-lexer.l"
{ return DAYS; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 208 "config-lexer.l"
{ return DAYS; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 209 "config-lexer.l"
{ return HOURS; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 210 "config-lexer.l"
{ return HOURS; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 211 "config-lexer.l"
{ return MINUTES; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 212 "config-lexer.l"
{ return MINUTES; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 213 "config-lexer.l"
{ return SECONDS; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 214 "config-lexer.l"
{ return SECONDS; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 216 "config-lexer.l"
{ return BYTES; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 217 "config-lexer.l"
{ return BYTES; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 218 "config-lexer.l"
{ return KBYTES; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 219 "config-lexer.l"
{ return KBYTES; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 220 "config-lexer.l"
{ return KBYTES; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 221 "config-lexer.l"
{ return KBYTES; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 222 "config-lexer.l"
{ return KBYTES; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 223 "config-lexer.l"
{ return MBYTES; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 224 "config-lexer.l"
{ return MBYTES; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 225 "config-lexer.l"
{ return MBYTES; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 226 "config-lexer.l"
{ return MBYTES; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 227 "config-lexer.l"
{ return MBYTES; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 229 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_HTTP;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 234 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_HTTPPOST;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 239 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_HTTPS;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 244 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_HTTPSPOST;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 249 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_SOCKS4;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 254 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_SOCKS5;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 259 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_WINGATE;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 264 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_ROUTER;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 269 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_DREAMBOX;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 275 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_SSH;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 280 "config-lexer.l"
{
                           yylval.number=1;
                           return NUMBER;
                         }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 284 "config-lexer.l"
{
                           yylval.number=1;
                           return NUMBER;
                         }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 288 "config-lexer.l"
{
                           yylval.number=1;
                           return NUMBER;
                         }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 295 "config-lexer.l"
{
                           yylval.number=0;
                           return NUMBER;
                         }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 300 "config-lexer.l"
{
                           yylval.number=0;
                           return NUMBER;
                         }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 305 "config-lexer.l"
{
                           yylval.number=0;
                           return NUMBER;
                         }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 310 "config-lexer.l"
{ return yytext[0]; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 311 "config-lexer.l"
{ if (conf_eof()) yyterminate(); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 313 "config-lexer.l"
ECHO;
	YY_BREAK
#line 1877 "config-lexer.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 526 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 526 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 525);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 313 "config-lexer.l"


static void
conf_include(void)
{
  char *p = NULL;
  char filenamebuf[512];

  if ((p = strchr(yytext, '<')) == NULL)
    *strchr(p = strchr(yytext, '"') + 1, '"') = '\0';
  else
    *strchr(++p, '>') = '\0';

  /* do stacking and co. */
  if (include_stack_ptr >= MAX_INCLUDE_DEPTH)
  {
    log_printf("CONFIG -> Includes nested too deep in %s", p);
    return;
  }

  if (*p == '/')  /* if it is an absolute path */
    snprintf(filenamebuf, sizeof(filenamebuf), "%s", p);
  else
    snprintf(filenamebuf, sizeof(filenamebuf), "%s/%s", HOPM_ETCDIR, p);

  FILE *tmp_fbfile_in = fopen(filenamebuf, "r");
  if (!tmp_fbfile_in)
  {
    log_printf("CONFIG -> Unable to read configuration file '%s': %s",
               filenamebuf, strerror(errno));
    return;
  }

  struct included_file *file = &include_stack[include_stack_ptr++];
  file->lineno = lineno;
  file->file = conf_file;
  file->state = YY_CURRENT_BUFFER;
  strlcpy(file->conffile, conffilebuf, sizeof(file->conffile));

  lineno = 1;
  conf_file = tmp_fbfile_in;
  strlcpy(conffilebuf, filenamebuf, sizeof(conffilebuf));

  yy_switch_to_buffer(yy_create_buffer(NULL, YY_BUF_SIZE));
}

static int
conf_eof(void)
{
  if (include_stack_ptr == 0)
    return 1;

  /* switch buffer */
  struct included_file *file = &include_stack[--include_stack_ptr];

  /* close current file */
  fclose(conf_file);

  /* switch buffers */
  yy_delete_buffer(YY_CURRENT_BUFFER);
  yy_switch_to_buffer(file->state);

  /* switch lineno */
  lineno = file->lineno;

  /* switch file */
  conf_file = file->file;

  strlcpy(conffilebuf, file->conffile, sizeof(conffilebuf));
  return 0;
}

