
#line 3 "config-lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (int) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 112
#define YY_END_OF_BUFFER 113
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[528] =
    {   0,
        7,    7,    0,    0,  113,  111,    7,    6,  111,    8,
      111,  111,    9,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,    3,    4,    3,    7,    6,    0,   10,
        8,    0,    1,    8,    9,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   25,    0,    0,
        0,    0,    0,   89,    0,    0,    0,    0,   94,    0,
        0,    0,    0,    0,    0,  109,    0,  107,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    2,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   76,    0,    0,    0,    0,    0,    0,    0,    0,
       29,    0,   31,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  110,    0,   42,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  104,    0,    0,   62,    0,
        0,    0,    0,    0,    0,    0,  106,    0,    0,   12,
        0,    0,   84,    0,    0,    0,   75,    0,    0,    0,
        0,    0,   78,   95,    0,   27,   28,    0,    0,    0,
       32,    0,    0,    0,    0,   34,    0,   35,    0,   38,

        0,   41,    0,    0,    0,    0,   47,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  105,   65,   66,    0,   74,    0,   70,    0,
        0,    0,    0,   83,    0,    0,    0,    0,    0,    0,
        0,    0,  108,   77,    0,   97,    0,   88,    0,   30,
        0,   93,    0,    0,   72,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   52,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       68,   73,    0,   69,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   24,    0,    0,   26,   87,

        0,    0,   92,    0,   80,   71,    0,    0,   40,    0,
        0,    0,    0,    0,    0,    0,    0,  102,    0,    0,
        0,   82,    0,   57,   99,  100,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   15,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   79,
        0,    0,   43,    0,   45,   46,    0,    0,    0,    0,
        0,   54,   55,   81,    0,    0,   61,    0,    0,    0,
      101,    0,    0,    0,    0,    0,    0,    0,   23,    0,
        0,  103,   96,    0,   86,   33,   91,   36,   39,   44,
       48,    0,   50,    0,    0,   56,    0,    0,    0,    0,

        0,   67,    0,    0,    0,    0,    0,   14,    0,    0,
        0,   19,    0,    0,    0,   98,   85,   90,    0,    0,
        0,    0,   58,    0,    0,    0,    0,    0,    5,    0,
        5,    0,    0,    0,    0,    0,   22,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   13,    0,
        0,    0,   20,   21,    0,   49,    0,    0,   59,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   60,
        0,    0,   11,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   18,    0,    0,    0,    0,    0,   16,

        0,   37,    0,    0,    0,    0,    0,   51,    0,    0,
        0,   17,    0,    0,    0,    0,    0,    0,   53,   63,
        0,    0,    0,    0,    0,   64,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    1,
        1,    6,    1,    1,    1,    7,    8,    9,    9,    9,
        9,   10,   11,   12,    9,    9,    9,    1,    1,   13,
        1,   14,    1,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,    1,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
        1,    1,    1,    1,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,    1,   50,   51,   52,   53,
       54,   55,   56,   57,   58,   59,   60,   61,   62,   63,
       64,   65,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[66] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[534] =
    {   0,
        0,    0,   63,   64, 1028, 1042, 1025,    0,   68,    0,
       45,   67,   67,   56,   65,   59,   68,   45,   70,   56,
       93,  107,  144,  112,  116,  184,  119,  151,  227,   54,
       69,  155,   74, 1042, 1042, 1017, 1022,    0,   93, 1042,
        0,   75, 1042,    0,  207,  121,  139,  128,  160,  143,
      167,  161,  146,  163,  178,  187,  186, 1042,  186,  189,
      192,  193,  213,  193,  196,  210,  213,  208,  205,  223,
      220,  237,  223,  230,  242,  230,  247, 1042,  253,  242,
      249,  264,  252,  259,  282,  254,  277,  279,  290,  279,
      279,  271,  277,  272,  276,  286,  297,  291,  305,  299,

      316, 1042,  315,  303,  297,  983,  321,  320,  313,  318,
      319,  317,  337,  339,  329,  324,  328,  333,  340,  132,
     1042,  334, 1042,  340,  342,  347,  982,  340,  361,  344,
      364,  351,  367,  370,  366,  368, 1042,  361, 1042,  373,
      366,  380,  381,  370,  372,  389,  378,  383,  378,  981,
      388,  391,  402,  386,  399, 1042,  404,  409,  980,  411,
      416,  405,  406,  415,  421,  412, 1042,  419,  429, 1042,
      416,  428,  421,  428,  442,  427, 1042,  434,  440,  437,
      437,  448,  439,  443,  444, 1042, 1042,  461,  466,  468,
     1042,  457,  471,  475,  461, 1042,  473, 1042,  481,  468,

      485, 1042,  476,  469,  479,  486, 1042,  482,  478,  485,
      488,  480,  500,  494,  500,  497,  503,  513,  502,  520,
      512,  525, 1042, 1042,  516,  513,  516,  537,  522,  522,
      525,  532,  536, 1042,  543,  536,  545,  979,  549,  547,
      555,  542, 1042, 1042,  548,  548,  560,  549,  546, 1042,
      567,  559,  554,  575,  563,  581,  580,  581,  577,  578,
      577,  584,  594,  590,  599,  588, 1042,  585,  588,  594,
      604,  609,  613,  598,   94,  598,  599,  617,  610,  628,
     1042, 1042,  611, 1042,  628,  615,  626,  628,  627,  638,
      637,  641,  635,  637,  637, 1042,  634,  639, 1042, 1042,

      635,  656, 1042,  642,  647, 1042,  658,  650, 1042,  651,
      654,  662,  671,  667,  670,  672,  680, 1042,  679,  682,
      673,  676,  687, 1042, 1042, 1042,  977,  679,  682,  683,
      691,  699,  700,  976,  693,  691, 1042,  975,  707,  696,
      703,  709,  714,  698,  704,  708,  723,  729,  729, 1042,
      731,  716, 1042,  736, 1042, 1042,  730,  737,  741,  745,
      729, 1042, 1042, 1042,  740,  746, 1042,  734,  737,  752,
     1042,  781,  752,  751,  751,  769,  750,  761, 1042,  774,
      775, 1042, 1042,  773,  775, 1042,  776,  974, 1042, 1042,
     1042,  781, 1042,  778,  797, 1042,  785,  788,  784,  796,

      793, 1042,  837,  820,  337,  806,  786, 1042,  796,  793,
      807, 1042,  805,  813,  810, 1042, 1042, 1042,  820,  818,
      831,  822, 1042,  827,  828,  840,  846,  291,  235,  212,
      210,  837,  837,  832,  847,  841, 1042,  835,  836,  852,
      839,  846,  855,  842,  853,  856,  856,  860, 1042,  869,
      862,  884, 1042, 1042,  888, 1042,  873,  152, 1042,  880,
      893,  892,  887,  882,  896,  888,  883,  899,  895,  899,
      906,  151,  885,  889,  150,  891,  903,  896,  909, 1042,
      898,  899, 1042,  920,  908,  915,  930,  921,  920,  940,
      943,  938,  941, 1042,  947,  952,  101,   97,  937, 1042,

      930, 1042,  945,  951,  952,  950,  956, 1042,  953,  954,
      958, 1042,  954,  955,  960,  967,  968,  975, 1042, 1042,
      985,  974,  985,  982,  984, 1042, 1042, 1037,  133, 1039,
      132,  100,   97
    } ;

static const flex_int16_t yy_def[534] =
    {   0,
      527,    1,  528,  528,  527,  527,  527,  529,  530,  531,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  529,  530,  527,
      531,  527,  527,  531,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,

      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,

      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,

      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,

      527,  527,  527,  532,  533,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  532,  532,  533,
      533,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,

      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,    0,  527,  527,  527,
      527,  527,  527
    } ;

static const flex_int16_t yy_nxt[1108] =
    {   0,
        6,    7,    8,    9,   10,    6,   11,   12,   13,   13,
       13,   13,    6,    6,   14,   15,   16,   17,   18,   19,
        6,   20,   21,   22,    6,   23,   24,   25,   26,    6,
       27,   28,   29,   30,   31,   32,    6,   33,    6,    6,
       14,   15,   16,   17,   18,   19,    6,   20,   21,   22,
        6,   23,   24,   25,   26,    6,   27,   28,   29,   30,
       31,   32,    6,   33,    6,   35,   35,   42,   36,   36,
       40,   40,   43,   46,   44,   45,   45,   45,   45,   48,
       51,   56,   53,   59,   57,   97,   52,   58,   60,   49,
       98,   47,  101,   42,   54,   40,   40,  430,   55,   46,

      428,  103,   50,  325,  326,   48,   51,   56,   53,   59,
       57,   97,   52,   58,   60,   49,   98,   47,  101,   61,
       54,   62,   64,   63,   55,   65,   73,  103,   50,   66,
       74,   67,   41,   38,   75,   77,  505,   85,  104,   76,
      504,  186,   78,  187,   79,   61,   86,   62,   64,   63,
       87,   65,   73,  105,  106,   66,   74,   67,   68,   69,
       75,   77,   70,   85,  104,   76,   71,   88,   78,   89,
       79,   72,   86,   99,  107,  108,   87,  100,   90,  105,
      106,  109,   91,  112,   68,   69,  110,  111,   70,  485,
      482,  469,   71,   88,  113,   89,  114,   72,   80,   99,

      107,  108,   81,  100,   90,  115,   82,  109,   91,  112,
      116,   83,  110,  111,   84,   45,   45,   45,   45,  117,
      113,  118,  114,  431,   80,  431,  119,  120,   81,  121,
      122,  115,   82,  123,  124,  125,  116,   83,  429,  126,
       84,   92,  128,  129,  127,  117,  130,  118,  133,   93,
      134,   94,  119,  120,  131,  121,  122,   95,  135,  123,
      124,  125,  136,  132,   96,  126,  137,   92,  128,  129,
      127,  138,  130,  141,  133,   93,  134,   94,  139,  142,
      131,  143,  144,   95,  135,  140,  145,  149,  136,  132,
       96,  150,  137,  151,  429,  155,  146,  138,  147,  141,

      156,  157,  158,  159,  139,  142,  152,  143,  144,  160,
      148,  140,  145,  149,  161,  162,  153,  150,  163,  151,
      154,  155,  146,  164,  147,  165,  156,  157,  158,  159,
      166,  168,  152,  169,  170,  160,  148,  172,  173,  174,
      161,  162,  153,  175,  163,  176,  154,  167,  177,  164,
      431,  165,  178,  180,  181,  182,  166,  168,  183,  169,
      170,  184,  185,  172,  173,  174,  188,  189,  190,  175,
      191,  176,  193,  167,  177,  194,  179,  195,  178,  180,
      181,  182,  196,  197,  183,  198,  199,  184,  185,  200,
      201,  202,  188,  189,  190,  203,  191,  204,  193,  205,

      206,  194,  207,  195,  208,  211,  209,  212,  196,  197,
      213,  198,  199,  210,  215,  200,  201,  202,  216,  217,
      218,  203,  219,  204,  220,  205,  206,  221,  207,  223,
      208,  211,  209,  212,  224,  225,  213,  226,  227,  210,
      215,  228,  229,  230,  216,  217,  218,  231,  219,  232,
      220,  233,  234,  221,  235,  223,  236,  237,  238,  239,
      224,  225,  241,  226,  227,  242,  243,  228,  229,  230,
      244,  245,  240,  231,  246,  232,  247,  233,  234,  248,
      235,  249,  236,  237,  238,  239,  250,  251,  241,  252,
      253,  242,  243,  254,  255,  256,  244,  245,  240,  257,

      246,  258,  247,  259,  260,  248,  261,  249,  262,  263,
      264,  265,  250,  251,  266,  252,  253,  267,  268,  254,
      255,  256,  269,  272,  270,  257,  271,  258,  273,  259,
      260,  274,  261,  275,  262,  263,  264,  265,  276,  277,
      266,  278,  280,  267,  268,  281,  279,  282,  269,  272,
      270,  283,  271,  284,  273,  285,  286,  274,  287,  275,
      288,  289,  290,  291,  276,  277,  293,  278,  280,  294,
      295,  281,  279,  282,  296,  297,  298,  283,  299,  284,
      300,  285,  286,  301,  287,  302,  288,  289,  290,  291,
      303,  304,  293,  305,  306,  294,  295,  307,  308,  309,

      296,  297,  298,  310,  299,  311,  300,  312,  313,  301,
      314,  302,  315,  316,  317,  318,  303,  304,  319,  305,
      306,  320,  321,  307,  308,  309,  322,  323,  324,  310,
      327,  311,  328,  312,  313,  329,  314,  330,  315,  316,
      317,  318,  331,  332,  319,  333,  334,  320,  321,  335,
      336,  337,  322,  323,  324,  338,  327,  339,  328,  342,
      340,  329,  343,  330,  344,  345,  346,  347,  331,  332,
      348,  333,  334,  341,  349,  335,  336,  337,  350,  351,
      352,  338,  353,  339,  354,  342,  340,  355,  343,  356,
      344,  345,  346,  347,  357,  358,  348,  359,  360,  341,

      349,  361,  362,  363,  350,  351,  352,  364,  353,  365,
      354,  367,  368,  355,  369,  356,  370,  371,  372,  374,
      357,  358,  375,  359,  360,  377,  378,  361,  362,  363,
      379,  380,  381,  364,  382,  365,  383,  367,  368,  384,
      369,  385,  370,  371,  372,  374,  386,  387,  375,  388,
      389,  377,  378,  390,  391,  392,  379,  380,  381,  393,
      382,  394,  383,  395,  396,  384,  400,  385,  397,  401,
      402,  406,  386,  387,  398,  388,  389,  399,  407,  390,
      391,  392,  403,  408,  404,  393,  412,  394,  413,  395,
      396,  409,  400,  405,  397,  401,  402,  406,  410,  414,

      398,  411,  415,  399,  407,  416,  417,  418,  420,  408,
      421,  422,  412,  423,  413,  424,  425,  409,  426,  427,
      432,  433,  434,  429,  410,  414,  435,  411,  415,  436,
      437,  416,  417,  418,  420,  438,  421,  422,  403,  423,
      404,  424,  425,  439,  426,  427,  432,  433,  434,  405,
      440,  441,  435,  442,  443,  436,  437,  444,  445,  446,
      447,  438,  448,  449,  450,  451,  452,  453,  454,  439,
      455,  456,  457,  458,  459,  460,  440,  441,  461,  442,
      443,  462,  463,  444,  445,  446,  447,  464,  448,  449,
      450,  451,  452,  453,  454,  465,  455,  456,  457,  458,

      459,  460,  466,  467,  461,  468,  470,  462,  463,  471,
      472,  473,  474,  464,  475,  476,  477,  478,  479,  480,
      481,  465,  483,  484,  486,  487,  488,  489,  466,  467,
      490,  468,  470,  491,  492,  471,  472,  473,  474,  493,
      475,  476,  477,  478,  479,  480,  481,  494,  483,  484,
      486,  487,  488,  489,  495,  496,  490,  497,  498,  491,
      492,  499,  500,  501,  502,  493,  503,  506,  507,  508,
      509,  510,  511,  494,  512,  513,  514,  515,  516,  517,
      495,  496,  518,  497,  498,  519,  520,  499,  500,  501,
      502,  521,  503,  506,  507,  508,  509,  510,  511,  522,

      512,  513,  514,  515,  516,  517,  523,  524,  518,  525,
      526,  519,  520,  419,  376,  373,  366,  521,  292,  222,
      214,  192,  171,   37,  102,  522,   37,  527,  527,  527,
      527,  527,  523,  524,  527,  525,  526,   34,   34,   39,
       39,    5,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,

      527,  527,  527,  527,  527,  527,  527
    } ;

static const flex_int16_t yy_chk[1108] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,   11,    3,    4,
        9,    9,   12,   14,   12,   13,   13,   13,   13,   15,
       16,   18,   17,   20,   19,   30,   16,   19,   20,   15,
       31,   14,   33,   11,   17,   39,   39,  533,   17,   14,

      532,   42,   15,  275,  275,   15,   16,   18,   17,   20,
       19,   30,   16,   19,   20,   15,   31,   14,   33,   21,
       17,   21,   22,   21,   17,   22,   24,   42,   15,   22,
       24,   22,  531,  529,   24,   25,  498,   27,   46,   24,
      497,  120,   25,  120,   25,   21,   27,   21,   22,   21,
       27,   22,   24,   47,   48,   22,   24,   22,   23,   23,
       24,   25,   23,   27,   46,   24,   23,   28,   25,   28,
       25,   23,   27,   32,   49,   50,   27,   32,   28,   47,
       48,   51,   28,   53,   23,   23,   52,   52,   23,  475,
      472,  458,   23,   28,   54,   28,   55,   23,   26,   32,

       49,   50,   26,   32,   28,   56,   26,   51,   28,   53,
       57,   26,   52,   52,   26,   45,   45,   45,   45,   59,
       54,   60,   55,  431,   26,  430,   61,   62,   26,   63,
       64,   56,   26,   65,   66,   67,   57,   26,  429,   68,
       26,   29,   69,   70,   68,   59,   71,   60,   73,   29,
       74,   29,   61,   62,   72,   63,   64,   29,   75,   65,
       66,   67,   76,   72,   29,   68,   77,   29,   69,   70,
       68,   79,   71,   80,   73,   29,   74,   29,   79,   81,
       72,   82,   83,   29,   75,   79,   84,   86,   76,   72,
       29,   87,   77,   88,  428,   90,   85,   79,   85,   80,

       91,   92,   93,   94,   79,   81,   89,   82,   83,   95,
       85,   79,   84,   86,   96,   97,   89,   87,   98,   88,
       89,   90,   85,   99,   85,  100,   91,   92,   93,   94,
      101,  103,   89,  104,  105,   95,   85,  107,  108,  109,
       96,   97,   89,  110,   98,  111,   89,  101,  112,   99,
      405,  100,  113,  114,  115,  116,  101,  103,  117,  104,
      105,  118,  119,  107,  108,  109,  122,  124,  125,  110,
      126,  111,  128,  101,  112,  129,  113,  130,  113,  114,
      115,  116,  131,  132,  117,  133,  134,  118,  119,  135,
      136,  138,  122,  124,  125,  140,  126,  141,  128,  142,

      143,  129,  144,  130,  145,  147,  146,  148,  131,  132,
      149,  133,  134,  146,  151,  135,  136,  138,  152,  153,
      154,  140,  155,  141,  157,  142,  143,  158,  144,  160,
      145,  147,  146,  148,  161,  162,  149,  163,  164,  146,
      151,  165,  166,  168,  152,  153,  154,  169,  155,  171,
      157,  172,  173,  158,  174,  160,  175,  176,  178,  179,
      161,  162,  180,  163,  164,  181,  182,  165,  166,  168,
      183,  184,  179,  169,  184,  171,  185,  172,  173,  188,
      174,  189,  175,  176,  178,  179,  190,  192,  180,  193,
      194,  181,  182,  195,  197,  199,  183,  184,  179,  200,

      184,  201,  185,  203,  204,  188,  205,  189,  206,  208,
      209,  210,  190,  192,  211,  193,  194,  212,  213,  195,
      197,  199,  214,  216,  215,  200,  215,  201,  217,  203,
      204,  218,  205,  219,  206,  208,  209,  210,  220,  221,
      211,  222,  225,  212,  213,  226,  222,  227,  214,  216,
      215,  228,  215,  229,  217,  230,  231,  218,  232,  219,
      233,  235,  236,  237,  220,  221,  239,  222,  225,  240,
      241,  226,  222,  227,  242,  245,  246,  228,  247,  229,
      248,  230,  231,  249,  232,  251,  233,  235,  236,  237,
      252,  253,  239,  254,  255,  240,  241,  256,  257,  258,

      242,  245,  246,  259,  247,  260,  248,  261,  262,  249,
      263,  251,  264,  265,  266,  268,  252,  253,  269,  254,
      255,  270,  271,  256,  257,  258,  272,  273,  274,  259,
      276,  260,  277,  261,  262,  278,  263,  279,  264,  265,
      266,  268,  280,  283,  269,  285,  286,  270,  271,  287,
      288,  289,  272,  273,  274,  290,  276,  291,  277,  293,
      292,  278,  294,  279,  295,  297,  298,  301,  280,  283,
      302,  285,  286,  292,  304,  287,  288,  289,  305,  307,
      308,  290,  310,  291,  311,  293,  292,  312,  294,  313,
      295,  297,  298,  301,  314,  315,  302,  316,  317,  292,

      304,  319,  320,  321,  305,  307,  308,  322,  310,  323,
      311,  328,  329,  312,  330,  313,  331,  332,  333,  335,
      314,  315,  336,  316,  317,  339,  340,  319,  320,  321,
      341,  342,  343,  322,  344,  323,  345,  328,  329,  346,
      330,  347,  331,  332,  333,  335,  348,  349,  336,  351,
      352,  339,  340,  354,  357,  358,  341,  342,  343,  359,
      344,  360,  345,  361,  365,  346,  368,  347,  366,  369,
      370,  373,  348,  349,  366,  351,  352,  366,  374,  354,
      357,  358,  372,  375,  372,  359,  377,  360,  378,  361,
      365,  376,  368,  372,  366,  369,  370,  373,  376,  380,

      366,  376,  381,  366,  374,  384,  385,  387,  392,  375,
      394,  395,  377,  397,  378,  398,  399,  376,  400,  401,
      406,  407,  409,  404,  376,  380,  410,  376,  381,  411,
      413,  384,  385,  387,  392,  414,  394,  395,  403,  397,
      403,  398,  399,  415,  400,  401,  406,  407,  409,  403,
      419,  420,  410,  421,  422,  411,  413,  424,  425,  426,
      427,  414,  432,  433,  434,  435,  436,  438,  439,  415,
      440,  441,  442,  443,  444,  445,  419,  420,  446,  421,
      422,  447,  448,  424,  425,  426,  427,  450,  432,  433,
      434,  435,  436,  438,  439,  451,  440,  441,  442,  443,

      444,  445,  452,  455,  446,  457,  460,  447,  448,  461,
      462,  463,  464,  450,  465,  466,  467,  468,  469,  470,
      471,  451,  473,  474,  476,  477,  478,  479,  452,  455,
      481,  457,  460,  482,  484,  461,  462,  463,  464,  485,
      465,  466,  467,  468,  469,  470,  471,  486,  473,  474,
      476,  477,  478,  479,  487,  488,  481,  489,  490,  482,
      484,  491,  492,  493,  495,  485,  496,  499,  501,  503,
      504,  505,  506,  486,  507,  509,  510,  511,  513,  514,
      487,  488,  515,  489,  490,  516,  517,  491,  492,  493,
      495,  518,  496,  499,  501,  503,  504,  505,  506,  521,

      507,  509,  510,  511,  513,  514,  522,  523,  515,  524,
      525,  516,  517,  388,  338,  334,  327,  518,  238,  159,
      150,  127,  106,   37,   36,  521,    7,    5,    0,    0,
        0,    0,  522,  523,    0,  524,  525,  528,  528,  530,
      530,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,

      527,  527,  527,  527,  527,  527,  527
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "config-lexer.l"
/*
 *  Copyright (c) 2002 Erik Fears
 *  Copyright (c) 2014-2020 ircd-hybrid development team
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301
 *  USA
 */
#define YY_NO_INPUT 1

#line 30 "config-lexer.l"
#include <stdio.h>
#include <string.h>

#include "compat.h"
#include "config.h"
#include "config-parser.h"  /* autogenerated header file */
#include "log.h"

/* libopm includes */
#include "libopm/src/opm_types.h"

#undef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) conf_yy_fatal_error(msg)

#undef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
  if (!(result = conf_yy_input(buf, max_size))) \
    YY_FATAL_ERROR("input in flex scanner failed");
#define MAX_INCLUDE_DEPTH 10


unsigned int lineno = 1;
char linebuf[512];
char conffilebuf[512];

static struct included_file
{
  YY_BUFFER_STATE state;
  unsigned int lineno;
  FILE *file;
  char conffile[512];
} include_stack[MAX_INCLUDE_DEPTH];

static unsigned int include_stack_ptr;


static void conf_include(void);
static int conf_eof(void);

static int
conf_yy_input(char *lbuf, unsigned int max_size)
{
  return fgets(lbuf, max_size, conf_file) == NULL ? 0 : strlen(lbuf);
}

static int
conf_yy_fatal_error(const char *msg)
{
  return 0;
}
#line 940 "config-lexer.c"
#line 941 "config-lexer.c"

#define INITIAL 0
#define IN_COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 88 "config-lexer.l"


#line 1160 "config-lexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (int) ((yy_c_buf_p) - (yytext_ptr));
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 528 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 527 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 90 "config-lexer.l"
{ BEGIN IN_COMMENT; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 91 "config-lexer.l"
{ BEGIN INITIAL;    }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 92 "config-lexer.l"
;  /* Eat everything but a newline */
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 93 "config-lexer.l"
{ ++lineno; }
	YY_BREAK
case YY_STATE_EOF(IN_COMMENT):
#line 94 "config-lexer.l"
{ BEGIN INITIAL; if (conf_eof()) yyterminate(); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 96 "config-lexer.l"
{ conf_include(); }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 97 "config-lexer.l"
{ strlcpy(linebuf, yytext + 1, sizeof(linebuf)); ++lineno; yyless(1); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 98 "config-lexer.l"
;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 99 "config-lexer.l"
;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 100 "config-lexer.l"
{ yylval.number = atoi(yytext); return NUMBER; }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 101 "config-lexer.l"
{ if (yytext[yyleng - 2] == '\\')
                  {
                    yyless(yyleng - 1);  /* Return last quote */
                    yymore();  /* Append next string */
                  }
                  else
                  {
                    yylval.string = yytext + 1;

                    if (yylval.string[yyleng - 2] != '"')
                      log_printf("CONFIG ->Unterminated character string");
                    else
                    {
                      unsigned int i = 0, j = 0;

                      yylval.string[yyleng - 2] = '\0';  /* Remove close quote */

                      for (; yylval.string[i] != '\0'; ++i, ++j)
                      {
                        if (yylval.string[i] != '\\')
                          yylval.string[j] = yylval.string[i];
                        else
                        {
                          ++i;

                          if (yylval.string[i] == '\0')  /* XXX: should not happen */
                          {
                            log_printf("CONFIG -> Unterminated character string");
                            break;
                          }

                          yylval.string[j] = yylval.string[i];
                        }
                      }

                      yylval.string[j] = '\0';
                      return STRING;
                    }
                  }
                }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 142 "config-lexer.l"
{ return ADDRESS_FAMILY; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 143 "config-lexer.l"
{ return AWAY;         }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 144 "config-lexer.l"
{ return BAN_UNKNOWN;  }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 145 "config-lexer.l"
{ return BLACKLIST;    }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 146 "config-lexer.l"
{ return CHANNEL;      }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 147 "config-lexer.l"
{ return COMMAND_INTERVAL; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 148 "config-lexer.l"
{ return COMMAND_QUEUE_SIZE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 149 "config-lexer.l"
{ return COMMAND_TIMEOUT; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 150 "config-lexer.l"
{ return CONNREGEX;    }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 151 "config-lexer.l"
{ return DNS_FDLIMIT;  }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 152 "config-lexer.l"
{ return DNS_TIMEOUT;  }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 153 "config-lexer.l"
{ return DNSBL_FROM;   }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 154 "config-lexer.l"
{ return DNSBL_TO;     }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 155 "config-lexer.l"
{ return EXEMPT;       }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 156 "config-lexer.l"
{ return FD;           }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 157 "config-lexer.l"
{ return INVITE;       }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 158 "config-lexer.l"
{ return IPV4;         }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 159 "config-lexer.l"
{ return IPV6;         }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 160 "config-lexer.l"
{ return IRC;          }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 161 "config-lexer.l"
{ return KLINE;        }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 162 "config-lexer.l"
{ return KEY;          }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 163 "config-lexer.l"
{ return MASK;         }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 164 "config-lexer.l"
{ return MAX_READ;     }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 165 "config-lexer.l"
{ return MODE;         }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 166 "config-lexer.l"
{ return NAME;         }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 167 "config-lexer.l"
{ return NEGCACHE;     }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 168 "config-lexer.l"
{ return NEGCACHE_REBUILD; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 169 "config-lexer.l"
{ return NICK;         }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 170 "config-lexer.l"
{ return NICKSERV;     }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 171 "config-lexer.l"
{ return NOTICE;       }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 172 "config-lexer.l"
{ return OPER;         }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 173 "config-lexer.l"
{ return OPM;          }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 174 "config-lexer.l"
{ return OPTIONS;      }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 175 "config-lexer.l"
{ return PASSWORD;     }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 176 "config-lexer.l"
{ return PERFORM;      }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 177 "config-lexer.l"
{ return PIDFILE;      }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 178 "config-lexer.l"
{ return PORT;         }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 179 "config-lexer.l"
{ return PROTOCOL;     }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 180 "config-lexer.l"
{ return READTIMEOUT;  }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 181 "config-lexer.l"
{ return REALNAME;     }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 182 "config-lexer.l"
{ return RECONNECTINTERVAL; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 183 "config-lexer.l"
{ return REPLY;        }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 184 "config-lexer.l"
{ return RSA_PRIVATE_KEY_FILE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 185 "config-lexer.l"
{ return SCANLOG;      }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 186 "config-lexer.l"
{ return SCANNER;      }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 187 "config-lexer.l"
{ return SENDMAIL;     }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 188 "config-lexer.l"
{ return SERVER;       }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 189 "config-lexer.l"
{ return TARGET_IP;    }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 190 "config-lexer.l"
{ return TARGET_PORT;  }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 191 "config-lexer.l"
{ return TARGET_STRING;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 192 "config-lexer.l"
{ return TIMEOUT;      }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 193 "config-lexer.l"
{ return TLS;          }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 194 "config-lexer.l"
{ return TLS_CERTIFICATE_FILE; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 195 "config-lexer.l"
{ return TLS_HOSTNAME_VERIFICATION; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 196 "config-lexer.l"
{ return TYPE;         }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 197 "config-lexer.l"
{ return USER;         }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 198 "config-lexer.l"
{ return USERNAME;     }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 199 "config-lexer.l"
{ return VHOST;        }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 201 "config-lexer.l"
{ return YEARS; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 202 "config-lexer.l"
{ return YEARS; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 203 "config-lexer.l"
{ return MONTHS; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 204 "config-lexer.l"
{ return MONTHS; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 205 "config-lexer.l"
{ return WEEKS; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 206 "config-lexer.l"
{ return WEEKS; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 207 "config-lexer.l"
{ return DAYS; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 208 "config-lexer.l"
{ return DAYS; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 209 "config-lexer.l"
{ return HOURS; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 210 "config-lexer.l"
{ return HOURS; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 211 "config-lexer.l"
{ return MINUTES; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 212 "config-lexer.l"
{ return MINUTES; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 213 "config-lexer.l"
{ return SECONDS; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 214 "config-lexer.l"
{ return SECONDS; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 216 "config-lexer.l"
{ return BYTES; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 217 "config-lexer.l"
{ return BYTES; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 218 "config-lexer.l"
{ return KBYTES; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 219 "config-lexer.l"
{ return KBYTES; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 220 "config-lexer.l"
{ return KBYTES; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 221 "config-lexer.l"
{ return KBYTES; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 222 "config-lexer.l"
{ return KBYTES; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 223 "config-lexer.l"
{ return MBYTES; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 224 "config-lexer.l"
{ return MBYTES; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 225 "config-lexer.l"
{ return MBYTES; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 226 "config-lexer.l"
{ return MBYTES; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 227 "config-lexer.l"
{ return MBYTES; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 229 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_HTTP;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 234 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_HTTPPOST;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 239 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_HTTPS;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 244 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_HTTPSPOST;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 249 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_SOCKS4;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 254 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_SOCKS5;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 259 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_WINGATE;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 264 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_ROUTER;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 269 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_DREAMBOX;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 275 "config-lexer.l"
{
                          yylval.number = OPM_TYPE_SSH;
                          return PROTOCOLTYPE;
                        }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 280 "config-lexer.l"
{
                           yylval.number=1;
                           return NUMBER;
                         }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 284 "config-lexer.l"
{
                           yylval.number=1;
                           return NUMBER;
                         }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 288 "config-lexer.l"
{
                           yylval.number=1;
                           return NUMBER;
                         }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 295 "config-lexer.l"
{
                           yylval.number=0;
                           return NUMBER;
                         }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 300 "config-lexer.l"
{
                           yylval.number=0;
                           return NUMBER;
                         }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 305 "config-lexer.l"
{
                           yylval.number=0;
                           return NUMBER;
                         }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 310 "config-lexer.l"
{ return yytext[0]; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 311 "config-lexer.l"
{ if (conf_eof()) yyterminate(); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 313 "config-lexer.l"
ECHO;
	YY_BREAK
#line 1877 "config-lexer.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 528 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 528 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 527);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 313 "config-lexer.l"


static void
conf_include(void)
{
  char *p = NULL;
  char filenamebuf[512];

  if ((p = strchr(yytext, '<')) == NULL)
    *strchr(p = strchr(yytext, '"') + 1, '"') = '\0';
  else
    *strchr(++p, '>') = '\0';

  /* do stacking and co. */
  if (include_stack_ptr >= MAX_INCLUDE_DEPTH)
  {
    log_printf("CONFIG -> Includes nested too deep in %s", p);
    return;
  }

  if (*p == '/')  /* if it is an absolute path */
    snprintf(filenamebuf, sizeof(filenamebuf), "%s", p);
  else
    snprintf(filenamebuf, sizeof(filenamebuf), "%s/%s", HOPM_ETCDIR, p);

  FILE *tmp_fbfile_in = fopen(filenamebuf, "r");
  if (!tmp_fbfile_in)
  {
    log_printf("CONFIG -> Unable to read configuration file '%s': %s",
               filenamebuf, strerror(errno));
    return;
  }

  struct included_file *file = &include_stack[include_stack_ptr++];
  file->lineno = lineno;
  file->file = conf_file;
  file->state = YY_CURRENT_BUFFER;
  strlcpy(file->conffile, conffilebuf, sizeof(file->conffile));

  lineno = 1;
  conf_file = tmp_fbfile_in;
  strlcpy(conffilebuf, filenamebuf, sizeof(conffilebuf));

  yy_switch_to_buffer(yy_create_buffer(NULL, YY_BUF_SIZE));
}

static int
conf_eof(void)
{
  if (include_stack_ptr == 0)
    return 1;

  /* switch buffer */
  struct included_file *file = &include_stack[--include_stack_ptr];

  /* close current file */
  fclose(conf_file);

  /* switch buffers */
  yy_delete_buffer(YY_CURRENT_BUFFER);
  yy_switch_to_buffer(file->state);

  /* switch lineno */
  lineno = file->lineno;

  /* switch file */
  conf_file = file->file;

  strlcpy(conffilebuf, file->conffile, sizeof(conffilebuf));
  return 0;
}

